### PR TITLE
fix cli translate-schema

### LINKED ISSUE #1159: CLI translate-schema command does not work in "json-to-cedar" direction
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Schemas and Validation

### Describe the bug

The CLI's `translate-schema` command fails when invoked with a JSON schema and `--direction json-to-cedar`:
```
$ cargo run -- translate-schema --schema ~/Downloads/photoflash.cedarschema.json --direction json-to-cedar
warning: /Users/adam.rothman/src/cedar/cedar-policy-core/Cargo.toml: unused manifest key: lints.rust.unexpected_cfgs.check-cfg
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
     Running `/Users/adam.rothman/src/cedar/target/debug/cedar translate-schema --schema /Users/adam.rothman/Downloads/photoflash.cedarschema.json --direction json-to-cedar`
  × error parsing schema: unexpected token `{`
  help: this API was expecting a schema in the Cedar schema format; did you mean to use a different function, which expects a JSON-format Cedar schema
```

### Expected behavior

The CLI should successfully parse the JSON schema file and output a translation to the human-readable format.

For example, it works fine when translating the [example human-readable schema](https://docs.cedarpolicy.com/schema/human-readable-schema.html#schema-examples) to JSON:
```
$ cargo run -- translate-schema --schema ~/Downloads/photoflash.cedarschema --direction cedar-to-json 
warning: /Users/adam.rothman/src/cedar/cedar-policy-core/Cargo.toml: unused manifest key: lints.rust.unexpected_cfgs.check-cfg
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
     Running `/Users/adam.rothman/src/cedar/target/debug/cedar translate-schema --schema /Users/adam.rothman/Downloads/photoflash.cedarschema --direction cedar-to-json`
{"PhotoFlash":{"entityTypes":{"Album":{"memberOfTypes":["Album"],"shape":{"type":"Record","attributes":{"account":{"type":"EntityOrCommon","name":"Account"},"private":{"type":"EntityOrCommon","name":"Bool"}}}},"User":{"memberOfTypes":["UserGroup"],"shape":{"type":"Record","attributes":{"department":{"type":"EntityOrCommon","name":"String"},"jobLevel":{"type":"EntityOrCommon","name":"Long"}}}},"Account":{"shape":{"type":"Record","attributes":{"admins":{"type":"Set","element":{"type":"EntityOrCommon","name":"User"},"required":false},"owner":{"type":"EntityOrCommon","name":"User"}}}},"Photo":{"memberOfTypes":["Album"],"shape":{"type":"Record","attributes":{"account":{"type":"EntityOrCommon","name":"Account"},"private":{"type":"EntityOrCommon","name":"Bool"}}}},"UserGroup":{}},"actions":{"uploadPhoto":{"appliesTo":{"resourceTypes":["Album"],"principalTypes":["User"],"context":{"type":"Record","attributes":{"authenticated":{"type":"EntityOrCommon","name":"Bool"},"photo":{"type":"Record","attributes":{"file_size":{"type":"EntityOrCommon","name":"Long"},"file_type":{"type":"EntityOrCommon","name":"String"}}}}}}},"viewPhoto":{"appliesTo":{"resourceTypes":["Photo"],"principalTypes":["User"],"context":{"type":"Record","attributes":{"authenticated":{"type":"EntityOrCommon","name":"Bool"}}}}},"listAlbums":{"appliesTo":{"resourceTypes":["Account"],"principalTypes":["User"],"context":{"type":"Record","attributes":{"authenticated":{"type":"EntityOrCommon","name":"Bool"}}}}}}}}
```

### Reproduction steps

1. Clone https://github.com/cedar-policy/cedar at latest master (3458cd20ec56756d164faf1108c20515bb839196 at time of report)
2. Download the example JSON format schema [here](https://docs.cedarpolicy.com/schema/json-schema.html#schema-examples); attached as [photoflash.cedarschema.json](https://github.com/user-attachments/files/16806244/photoflash.cedarschema.json)
3. In the `cedar-policy-cli` directory, run `cargo run -- translate-schema --schema ~/Downloads/photoflash.cedarschema.json --direction json-to-cedar`
4. Error

### Code Snippet

_No response_

### Log output

_No response_

### Additional configuration

_No response_

### Operating  System

macOS Sonoma 14.6.1

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by khieta**
## Description of changes

Fixes a behavior change introduced by #1114, which switched `SchemaFragment::from_str` to expect the Cedar format (it previously expected JSON). This PR is only on `main`, so it doesn't affect released code. Added a test case to avoid breaking this again in the future.

## Issue #, if available

Resolves #1159 

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [X] A change (breaking or otherwise) that only impacts unreleased or experimental code.

I confirm that this PR (choose one, and delete the other options):

- [X] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [X] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

### CODE REVIEW

File: cedar-policy-validator/src/cedar_schema/fmt.rs [hunk 1]
```diff
@@ -32,7 +32,7 @@ impl<N: Display> Display for json_schema::Fragment<N> {
         for (ns, def) in &self.0 {
             match ns {
                 None => write!(f, "{def}")?,
-                Some(ns) => write!(f, "namespace {ns} {{\n{def}}}")?,
+                Some(ns) => write!(f, "namespace {ns} {{\n{def}}}\n")?,
```
Comment (khieta) [inline cedar-policy-validator/src/cedar_schema/fmt.rs:35]: Fixes weird formatting noted in https://github.com/cedar-policy/cedar/issues/682#issuecomment-2059687349

File: cedar-policy-cli/tests/sample.rs [hunk 2]
```diff
@@ -1126,3 +1126,31 @@ fn test_translate_policy() {
...
+    // cedar -> json
+    assert_cmd::Command::cargo_bin("cedar")
+        .expect("bin exists")
+        .arg("translate-schema")
+        .arg("--direction")
+        .arg("json-to-cedar")
+        .arg("-s")
+        .arg(json_filename)
+        .assert()
+        .code(0);
```
Comment (khieta) [inline cedar-policy-cli/tests/sample.rs:1155]: I'm only checking the return code here since checking for equality of input/output would require storing the schemas in the format output by `Display`, which is ugly 😞 See #682 and #1161 for specific complaints.

**Review by john-h-kastner-aws — APPROVED** [review]

**Review by cdisselkoen — APPROVED** [review]
Great changes
