### PR TITLE
Remove Unknown expression from EST for functions named "unknown"

### LINKED ISSUE #1061: EST parser and Cedar parser return different ASTs on policies with functions named "unknown"
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

The following policy EST fails [this check](https://github.com/cedar-policy/cedar-spec/blob/main/cedar-drt/fuzz/src/parsing_utils.rs#L36-L39) in convert-policy-json-to-cedar.

```
{
    "effect": "permit",
    "principal": {  "op": "All"  },
    "action": {  "op": "All"   },
    "resource": {  "op": "All"  },
    "conditions": [
        {
            "kind": "when",
            "body": {
                "unknown": [
                    {
                        "Value": ""
                    }
                ]
            }
        }
    ]
}
```
This is due to the difference in AST expression kind built when parsing the EST (Unknown) vs parsing Cedar (ExtensionFunctionApp).

Also related to #891 

### Expected behavior

.

### Reproduction steps

.

### Code Snippet

_No response_

### Log output

_No response_

### Additional configuration

_No response_

### Operating  System

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by vasumv**
Fixes #1061 

## Description of changes
Removes `ExprNoExt::Unknown` from `est`. Conversion from `ast::Expr::Unknown` returns an extension function call with one arg literal of the unknown name. 

Test case included similar to input found by DRT.

## Issue #, if available
#1061 

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A change (breaking or otherwise) that only impacts unreleased or experimental code.

I confirm that this PR (choose one, and delete the other options):

- [x] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

### CODE REVIEW

File: cedar-policy-core/src/est/expr.rs [hunk 1]
```diff
@@ -1611,7 +1602,6 @@ fn maybe_with_parens(f: &mut std::fmt::Formatter<'_>, expr: &Expr) -> std::fmt::
         Expr::ExprNoExt(ExprNoExt::Value(_)) |
         Expr::ExprNoExt(ExprNoExt::Var(_)) |
         Expr::ExprNoExt(ExprNoExt::Slot(_)) |
-        Expr::ExprNoExt(ExprNoExt::Unknown { .. }) => write!(f, "{expr}"),
```
Comment (john-h-kastner-aws) [inline cedar-policy-core/src/est/expr.rs:1614]: shouldn't delete the `write!` part of this line

File: cedar-policy-core/src/est/expr.rs [hunk 2]
```diff
@@ -735,7 +721,13 @@ impl From<ast::Expr> for Expr {
             ast::ExprKind::Lit(lit) => lit.into(),
             ast::ExprKind::Var(var) => var.into(),
             ast::ExprKind::Slot(slot) => slot.into(),
-            ast::ExprKind::Unknown(ast::Unknown { name, .. }) => Expr::unknown(name),
+            ast::ExprKind::Unknown(ast::Unknown { name, .. }) => {
```
Comment (john-h-kastner-aws) [inline cedar-policy-core/src/est/expr.rs:724]: The natural follow-up question is if we need `ast::ExprKind::Unknown`. I'm not sure myself

File: cedar-policy-core/src/est/expr.rs [hunk 3]
```diff
@@ -108,12 +108,6 @@ pub enum ExprNoExt {
     Var(ast::Var),
     /// Template slot
     Slot(#[cfg_attr(feature = "wasm", tsify(type = "string"))] ast::SlotId),
-    /// Unknown (for partial evaluation)
-    Unknown {
-        /// Name of the unknown
-        #[cfg_attr(feature = "wasm", tsify(type = "string"))]
-        name: SmolStr,
```
Comment (john-h-kastner-aws) [inline cedar-policy-core/src/est/expr.rs:115]: Looking at this unknown variant closer, I see that it would accept `{ "unknown": "foo" }`, but the extension form accepts `{"unknown": [ {"value": "foo" }]}`. So, we are breaking one representation of unknown in the est. This is probably fine based on the justification that it's an experimental feature (and we're coming up on a major version anyways)

Comment (vasumv) [reply cedar-policy-core/src/est/expr.rs:115]: Yes, good catch.

File: cedar-policy-core/src/est/expr.rs (hunk 2 above)
Comment (vasumv) [reply cedar-policy-core/src/est/expr.rs:724]: I think there are still many dependencies on `ast::ExprKind::Unknown`, don't think we should remove it for this PR

File: cedar-policy-core/src/est/expr.rs [hunk 4]
```diff
@@ -346,11 +340,6 @@ impl Expr {
         Expr::ExprNoExt(ExprNoExt::Slot(slot))
     }
 
-    /// Partial-evaluation unknowns
-    pub fn unknown(name: impl Into<SmolStr>) -> Self {
-        Expr::ExprNoExt(ExprNoExt::Unknown { name: name.into() })
-    }
```
Comment (cdisselkoen) [inline cedar-policy-core/src/est/expr.rs:352]: If it would be convenient, it would be possible to keep this constructor and just change its implementation to produce the new representation of `unknown`

File: cedar-policy-core/src/est/expr.rs [hunk 5]
```diff
@@ -735,7 +721,13 @@ impl From<ast::Expr> for Expr {
...
             ast::ExprKind::Var(var) => var.into(),
             ast::ExprKind::Slot(slot) => slot.into(),
-            ast::ExprKind::Unknown(ast::Unknown { name, .. }) => Expr::unknown(name),
+            ast::ExprKind::Unknown(ast::Unknown { name, .. }) => {
+                // Create an extension call with one arg, which is the name of the unknown
+                Expr::ext_call(
+                    "unknown".to_string().into(),
+                    vec![Expr::lit(CedarValueJson::String(name))],
+                )
+            }
```
Comment (cdisselkoen) [inline cedar-policy-core/src/est/expr.rs:730]: continuing my earlier comment, then we wouldn't need this change at all; this could still be a call to `Expr::unknown`

**Review by cdisselkoen — APPROVED** [review]

**Review by john-h-kastner-aws — APPROVED** [review]
