### PR TITLE
Check undeclared entity types in common types when performing schema validation

### LINKED ISSUE #1068: Validator should error on JSON schema containing unused, undeclared common type of type `Entity`
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Schemas and Validation

### Describe the bug

The following JSON schema validates, even though the entity type `B` is undeclared.
```
{
    "": {
        "commonTypes": {
            "A": {
                "type": "Entity",
                "name": "B"
            }
        },
        "entityTypes": {},
        "actions": {}
    }
}
```

### Expected behavior

Validator should return an error that `B` is an undeclared entity type. Note that if this common type is used in a policy, the validator will properly reject this schema.

### Reproduction steps

I used the validation from the `cedar-policy-cli@3.2.1`

1. Save the initial schema above as `schema.json`
2. Create an empty policy file `policy.cedar`
3. `cedar validate -s schema.json -p policy.cedar --schema-format json`

### Code Snippet

_No response_

### Log output

_No response_

### Additional configuration

_No response_

### Operating  System

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by vasumv**
## Description of changes
Fixes #1068 

Checks undeclared types in common types during schema validation. The validator will now reject inputs such as the following:
```
{
  "": {
    "commonTypes": {
      "A": {
        "type": "Entity",
        "name": "B"
      }
    },
    "entityTypes": {},
    "actions": {}
  }
```
with an error that entity type `B` is undeclared. Added tests to check these cases.

## Issue #, if available
#1068 

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A bug fix or other functionality change requiring a patch to `cedar-policy`.

I confirm that this PR (choose one, and delete the other options):

- [x] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

### CODE REVIEW

**Comment by vasumv** [comment]
From discussion, will include this for 4.0 but will hold off on back-porting in 2.X and 3.X

File: cedar-policy-validator/src/schema.rs [hunk 1]
```diff
@@ -411,6 +412,7 @@ impl ValidatorSchema {
         undeclared_parent_entities: impl IntoIterator<Item = EntityType>,
         action_ids: &HashMap<EntityUID, ValidatorActionId>,
         undeclared_parent_actions: impl IntoIterator<Item = EntityUID>,
+        common_types: &HashMap<&Name, Type>,
```
Comment (shaobo-he-aws) [inline cedar-policy-validator/src/schema.rs:415]: Nit: we don't need reference to hashmap keys here. Maybe change it to an iterator?

**Review by shaobo-he-aws — APPROVED** [review]
LGTM.

File: cedar-policy-validator/src/schema.rs [hunk 2]
```diff
@@ -434,6 +436,11 @@ impl ValidatorSchema {
             }
         }
 
+        // Check for undeclared entity types within common types.
+        for common_type in common_types {
+            Self::check_undeclared_in_type(&common_type, entity_types, &mut undeclared_e);
+        }
```
Comment (cdisselkoen) [inline cedar-policy-validator/src/schema.rs:442]: Do we also need to check for undeclared _common_ types within common types?

**Review by cdisselkoen — APPROVED** [review]

File: cedar-policy-validator/src/schema.rs (hunk 2 above)
Comment (vasumv) [reply cedar-policy-validator/src/schema.rs:442]: That's already checked by the common type resolver ([link](https://github.com/cedar-policy/cedar/blob/eb740c26a96f5763e8662d02148d76b72327eee2/cedar-policy-validator/src/schema.rs#L805-L815))
