### PR TITLE
Error EST to AST conversion when there are slots in conditions

### LINKED ISSUE #606: Templates constructed from EST do not error on slots in condition
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

```rust
#[test]
fn est_template() {
    let est_json = serde_json::json!({
        "effect": "permit",
        "principal": { "op": "All" },
        "action": { "op": "All" },
        "resource": { "op": "All" },
        "conditions": [
            {
                "kind": "when",
                "body": {
                    "==": {
                        "left": { "Var": "principal" },
                        "right": { "Slot": "?principal" }
                    }
                }
            }
        ]
    });

    let tid = PolicyId::new("t0");
    // We should get an error here after trying to construct a template with a slot in the condition
    let template = Template::from_json(Some(tid.clone()), est_json).unwrap();

    let mut ps = PolicySet::new();
    ps.add_template(template).unwrap();
    let lid = PolicyId::new("l0");
    ps.link(
        tid,
        lid,
        [(SlotId::principal(), r#"User::"jane""#.parse().unwrap())].into(),
    )
    .unwrap();

    let auth = Authorizer::new();
    let r = Request::new(
        Some(r#"User::"jane""#.parse().unwrap()),
        Some(r#"Action::"take""#.parse().unwrap()),
        Some(r#"Thing::"thing""#.parse().unwrap()),
        Context::empty(),
        None,
    )
    .unwrap();
    assert_eq!(
        auth.is_authorized(&r, &ps, &Entities::empty()).decision,
        Decision::Allow
    );
}
```

### PR DESCRIPTION
**Pull request by shaobo-he-aws**
## Description of changes

fixes #606

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A bug fix or other functionality change requiring a patch to `cedar-policy`.

I confirm that this PR (choose one, and delete the other options):

- [x] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: cedar-policy-core/src/est.rs [hunk 1]
```diff
@@ -243,11 +243,24 @@ impl Policy {
 }
 
 impl Clause {
+    fn filter_slots(e: ast::Expr, is_when: bool) -> Result<ast::Expr, FromJsonError> {
+        let slots: Vec<_> = e.slots().map(|s| *s).collect();
+        if let Some(slot) = slots.first() {
```
Comment (cdisselkoen) [inline cedar-policy-core/src/est.rs:248]: I believe we can avoid collecting into a Vec here (and thus allocating memory).

```suggestion
        let slots = e.slots().copied();
        if let Some(slot) = slots.next() {
```

**Review by cdisselkoen — APPROVED** [review]

**Review by john-h-kastner-aws — APPROVED** [review]

File: cedar-policy-core/src/est.rs (hunk 1 above)
Comment (shaobo-he-aws) [reply cedar-policy-core/src/est.rs]: It doesn't seem to work because `e` is still borrowed, which is moved in one of the if branches.

Comment (cdisselkoen) [reply cedar-policy-core/src/est.rs]: What if 
```
let first_slot = e.slots().copied().next();
if let Some(slot) = first_slot {
```
Since the type of `first_slot` is now `Option<Slot>`, it doesn't keep `e` borrowed

Comment (shaobo-he-aws) [reply cedar-policy-core/src/est.rs]: Right. Please see the latest commit.

**Review by andrewmwells-amazon — APPROVED** [review]
