### PR TITLE
SymCC: Fix a cex generation bug

### LINKED ISSUE #1799: Spurious counterexamples generated by SymCC
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [x] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

SymCC produces a spurious counterexample when checking always denies on the following schema and policy,

```
Schema: {
      "entityTypes": {
        "a": {
          "shape": {
            "type": "Record",
            "attributes": {
              "r": {
                "type": "Boolean"
              }
            }
          },
          "tags": {
            "type": "Extension",
            "name": "datetime"
          }
        }
      },
      "actions": {
        "action": {
          "appliesTo": {
            "resourceTypes": [
              "a"
            ],
            "principalTypes": [
              "a"
            ]
          },
          "memberOf": []
        }
      }
    }

Policies: permit(
      principal,
      action in [Action::"action"],
      resource
    ) when {
      ((true && (a::"*"["r"])) && true) && true
    };
```

The entities of the counterexample is as follows,
```
entities:
a::"": {"r": true}
Action::"action"
```

It doesn't include the entity literal `a::"*"`. Lean was able to give a correct counterexample.

### Expected behavior

N/A

### Reproduction steps

N/A

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

### Additional configuration

_No response_

### Operating  System

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by zhengyao-lin**
## Description of changes

Fixes #1799, which was due to incorrect EUID collection during concretization: https://github.com/cedar-policy/cedar/blob/1b0f697841eaea87bd7e24bc7887068f3f1ee6da/cedar-policy-symcc/src/symcc/concretizer.rs#L427

This produced an empty footprint in the case of #1799, because `a::"*"["r"]` compiles to a literal `true` term. However, we do need the `a::"*"` entity for a well-formed counterexample.

I changed it to match the Lean model (which is almost always correct, unsurprisingly), so that the EUIDs are directly collected from the [`Expr` without going through `footprint`](https://github.com/cedar-policy/cedar-spec/blob/c68f13028ac563508df4ac6dc71ba89f57b26454/cedar-lean/Cedar/SymCC/Concretizer.lean#L234).

I also did some more refactoring to add an `extractor` module to match the latest version of the Lean model.

### CODE REVIEW

**Comment by shaobo-he-aws** [comment]
I ran DRT on your branch and discovered an error. Cex generation failed for the following schema and policy,

```
Schema: {
"entityTypes": {
"a": { "shape": {  "type": "Record", "attributes": { "ZB": { "type": "Record", "attributes": {}, "required": false }
            }
          }
        }
      },
      "actions": {
        "action": {
          "appliesTo": {
            "resourceTypes": [
              "a"
            ],
            "principalTypes": [
              "a"
            ]
          },
          "memberOf": []
        }
      }
    }
 Policies: @r("\u{1a}\u{19}\u{19}")
    @r00000000("")
    permit(
      principal,
      action in [Action::"action"],
      resource
    ) when {
      true && (a::"" has "ZB")
    };
```

The error message is: `failed to decode model: Unknown SMT literal: R0`

**Comment by shaobo-he-aws** [comment]
Lean also fails on the example above. Error message:

```
LeanBackendError(
        "IO error: Model decoding failed: expected enum id, given \"R0\"\n (\n(define-fun f0 ((_arg_1 E2)) R1 (R1 ((as some (Option R0)) R0)))\n)\n",
    )
```

Tagging @emina to confirm if it's expected.

**Comment by zhengyao-lin** [comment]
Could be wrong but I believe it's because the decoder incorrectly handles empty record values (separate issue from this PR).
In the example, the empty record type in the schema is encoded as
```
; {}
(declare-datatype R0 (
  (R0)))
```
and the model output by cvc5 is
```
(
(define-fun f0 ((_arg_1 E2)) R1 (R1 ((as some (Option R0)) R0)))
)
```
where `R0` is directly used as a symbol as opposed to an application `(R0 ...)` like non-empty records.

In the case of a single symbol, both Lean and Rust decoders only consider it as [true/false/enum literal](https://github.com/cedar-policy/cedar-spec/blob/c68f13028ac563508df4ac6dc71ba89f57b26454/cedar-lean/Cedar/SymCC/Decoder.lean#L224-L226), hence not being able to recognize it as a record value.

Attempts to fix this issue: Rust #1801, Lean https://github.com/cedar-policy/cedar-spec/pull/721

File: cedar-policy-symcc/src/symcc/concretizer.rs [hunk 1]
```diff
@@ -415,17 +417,86 @@ impl SymEntities {
...
-    pub fn concretize<'a>(
+    /// Corresponds to `Prim.entityUIDs` in `Concretize.lean`
+    fn get_all_entity_uids_in_literal(lit: &Literal, uids: &mut BTreeSet<EntityUid>) {
+        if let Literal::EntityUID(euid) = lit {
+            uids.insert(euid.as_ref().clone().into());
+        }
+    }
+
+    /// Corresponds to `Expr.entityUIDs` in `Concretize.lean`
+    fn get_all_entity_uids_in_expr(
```
Comment (cdisselkoen) [inline cedar-policy-symcc/src/symcc/concretizer.rs]: Would it simplify things to define this in terms of the already-existing `ExprVisitor` (see [here](https://github.com/cedar-policy/cedar/blob/1b0f697841eaea87bd7e24bc7887068f3f1ee6da/cedar-policy-core/src/ast/expr_visitor.rs#L4))?

File: cedar-policy-symcc/src/symcc/extractor.rs [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+    }
+}
+
+impl Interpretation<'_> {
+    /// Our acyclicity constraints only apply to the footprint,
+    /// but SMT solver may choose to add additional elements
+    /// that introduce cycles in the ancestor functions.
+    ///
+    /// This function repairs that by mappinng all inputs in the
+    /// ancestor functions taht are not in the footprint to empty sets
```
Comment (cdisselkoen) [inline cedar-policy-symcc/src/symcc/extractor.rs]:
```suggestion
    /// ancestor functions that are not in the footprint to empty sets
```

**Review by cdisselkoen — APPROVED** [review]

File: cedar-policy-symcc/src/symcc/concretizer.rs (hunk 1 above)
Comment (shaobo-he-aws) [reply cedar-policy-symcc/src/symcc/concretizer.rs]: I vaguely recall that Andrew wrote something similar.

Comment (cdisselkoen) [reply cedar-policy-symcc/src/symcc/concretizer.rs]: I think the one Andrew wrote is [this](https://docs.rs/cedar-policy/latest/cedar_policy/struct.Policy.html#method.entity_literals)?  For [reasons](https://github.com/cedar-policy/cedar/pull/1648#discussion_r2124731064), that's not implemented in terms of ExprVisitor.  We could use that here too, though, not sure which is better

**Review by shaobo-he-aws — APPROVED** [review]
