### PR TITLE
Fix #299, condition of `if` not being partial evaluated

### LINKED ISSUE #299: Partial evaluation invariant violated, causes crash in debug mode,
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Policy Evaluation

### Describe the bug

Running the following test:

    #[test]
    fn partial_value_invariant_maintained() {
        let es = Entities::from_entities([
            Entity::new(r#"R::a::"u1c""#.parse().unwrap(), HashMap::new(), HashSet::new()),
            Entity::new(r#"R::a::"""#.parse().unwrap(), HashMap::new(), HashSet::new()),
        ], TCComputation::ComputeNow)
            .unwrap();
        let exts = Extensions::none();
        let q = Request::new_with_unknowns(
            EntityUIDEntry::concrete(r#"R::a::"u1c""#.parse().unwrap()),
            EntityUIDEntry::concrete("R::Action::\"action\"".parse().unwrap()),
            EntityUIDEntry::Unknown,
            Some(Context::empty()));
        let eval = Evaluator::new(&q, &es, &exts).unwrap();

        let pset: &str = r#"forbid(
            principal in R::a::"u1c",
            action in [R::Action::"action"],
            resource == R::a::""
          ) when {
            ((true && (!(!(resource in [])))) &&
            ((if (resource in []) then (if true then principal else principal) else R::a::"") in [action])) && (resource in resource)
          };"#;

        let static_policy =
        parser::parse_policy(Some("id".into()), pset)
            .expect("Failed to parse");
        let r = eval.partial_evaluate(&static_policy.into())
            .expect("Failed to evaluate");
        println!("{:?}", r);
    }

results in a crash.

The crash seems to happen specifically in the `into()` call in `eval_if`, which converts an expression into a partial value. The invariant that all partial values contain at least one unknown is violated.

### Expected behavior

It should output the residual `if (unknown("resource") in []) then R::a::"u1c" else R::a::""`. Alternatively, it could be more precise and output the concrete value `R::a::""`.

### Reproduction steps

Run the provided test in `evaluator.rs`.

### Code Snippet

See details

### Log output

```
running 1 test
thread 'evaluator::test::partial_ite' panicked at 'assertion failed: e.is_unknown()', cedar-policy-core/src/ast/value.rs:102:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: <cedar_policy_core::ast::value::PartialValue as core::convert::From<cedar_policy_core::ast::expr::Expr>>::from
             at ./src/ast/value.rs:102:9
   4: <T as core::convert::Into<U>>::into
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/convert/mod.rs:727:9
   5: cedar_policy_core::evaluator::Evaluator::eval_if
             at ./src/evaluator.rs:628:29
   6: cedar_policy_core::evaluator::Evaluator::partial_interpret
             at ./src/evaluator.rs:270:18
   7: cedar_policy_core::evaluator::Evaluator::partial_interpret
             at ./src/evaluator.rs:348:21
   8: cedar_policy_core::evaluator::Evaluator::run_to_error
             at ./src/evaluator.rs:218:15
   9: cedar_policy_core::evaluator::Evaluator::partial_interpret
             at ./src/evaluator.rs:276:25
  10: cedar_policy_core::evaluator::Evaluator::partial_interpret
             at ./src/evaluator.rs:272:23
  11: cedar_policy_core::evaluator::Evaluator::run_to_error
             at ./src/evaluator.rs:218:15
  12: cedar_policy_core::evaluator::Evaluator::partial_interpret
             at ./src/evaluator.rs:276:25
  13: cedar_policy_core::evaluator::Evaluator::partial_evaluate
             at ./src/evaluator.rs:204:15
  14: cedar_policy_core::evaluator::test::partial_ite
             at ./src/evaluator.rs:4800:17
  15: cedar_policy_core::evaluator::test::partial_ite::{{closure}}
             at ./src/evaluator.rs:4774:22
  16: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test evaluator::test::partial_ite ... FAILED
```

### Additional configuration

_No response_

### Operating  System

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by prakol16**
## Description of changes
Ensure that the residual condition is the one being propagated in the return value of partial evaluation. This fixes a potential crash that occurs due to the partial value invariant being violated. Also adds a test case.

## Issue #, if available

#299 

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A bug fix or other functionality change requiring a patch to `cedar-policy`.

I confirm that this PR (choose one, and delete the other options):

- [x] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: cedar-policy-core/src/evaluator.rs [hunk 1]
```diff
@@ -619,13 +619,13 @@ impl<'q, 'e> Evaluator<'e> {
                     self.partial_interpret(alternative, slots)
                 }
             }
-            PartialValue::Residual(_) => {
+            PartialValue::Residual(guard) => {
```
Comment (shaobo-he-aws) [inline cedar-policy-core/src/evaluator.rs:622]: Minor: Can we rename it to `condition`?

**Review by shaobo-he-aws — APPROVED** [review]

**Review by aaronjeline — APPROVED** [review]
