### PR TITLE
Unescape raw strings during CST to EST conversion and add JSON representation of pattern literal

### LINKED ISSUE #618: Escapes sequences mangled by JSON round-trip
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

Starting with policy containing a string with an escape sequence `"\n"`, if we serialize the policy to JSON and then construct a new policy from that JSON, the string becomes `"\\n"`.  

```rust
    let policy_src = r#"permit(principal, action, resource) when { "\n" };"#;
    let p1 = Policy::from_str(policy_src).unwrap();
    println!("{p1}"); // permit(principal, action, resource) when { "\n" };

    let json = p1.to_json().unwrap();
    println!("{json}"); // {"effect":"permit","principal":{"op":"All"},"action":{"op":"All"},"resource":{"op":"All"},"conditions":[{"kind":"when","body":{"Value":"\\n"}}]}

    let p2 = Policy::from_json(None, json).unwrap();
    println!("{p2}"); // permit(principal, action, resource) when { "\\n" };
```

### Expected behavior

JSON roundtrip should produce an equivalent policy 

### Reproduction steps

.

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

### Additional configuration

_No response_

### Operating  System

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by shaobo-he-aws**
## Description of changes

Fixes #618

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A breaking change requiring a major version bump to `cedar-policy` (e.g., changes to the signature of an existing API).
- [ ] A backwards-compatible change requiring a minor version bump to `cedar-policy` (e.g., addition of a new API).
- [ ] A bug fix or other functionality change requiring a patch to `cedar-policy`.
- [ ] A change "invisible" to users (e.g., documentation, changes to "internal" crates like `cedar-policy-core`, `cedar-validator`, etc.)
- [ ] A change (breaking or otherwise) that only impacts unreleased or experimental code.

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).
- [ ] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.
- [ ] Requires updates, and I have made / will make these updates myself. (Please include in your description a timeline or link to the relevant PR in `cedar-spec`, and how you have tested that your updates are correct.)
- [ ] Requires updates, but I do not plan to make them in the near future. (Make sure that your changes are hidden behind a feature flag to mark them as experimental.)
- [ ] I'm not sure how my change impacts `cedar-spec`. (Post your PR anyways, and we'll discuss in the comments.)

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: cedar-policy/src/tests.rs [hunk 1]
```diff
@@ -3258,3 +3258,31 @@ mod error_source_tests {
         }
     }
 }
+
+mod issue_618 {
```
Comment (john-h-kastner-aws) [inline cedar-policy/src/tests.rs:3262]: I think it's worth being exhaustive here. These extra test cases come to mind.

* `"" like "\n"`
* `principal has "\n"`
* `principal["\n"]`
* `{"\n": 0}`
* `@annotation("\n")`

File: cedar-policy-core/src/est/expr.rs [hunk 2]
```diff
@@ -1088,20 +1089,31 @@ fn interpret_primary(
...
                                 name,
-                                ast::Eid::new(eid.clone()),
+                                ast::Eid::new(eid),
                             )),
-                        })))
-                    }
+                        }))),
+                        Err(unescape_errs) => {
+                            errs.extend(unescape_errs.into_iter().map(|err| {
+                                crate::parser::err::ParseError::from(
```
Comment (john-h-kastner-aws) [inline cedar-policy-core/src/est/expr.rs:1110]: This could probably be just `into` like in the `cst::Literal::Str` case below

File: cedar-policy/src/tests.rs [hunk 3]
```diff
@@ -3258,3 +3258,31 @@ mod error_source_tests {
...
+
+    #[test]
+    fn string_escapes() {
+        let policy_src = r#"permit(principal, action, resource) when { "\n" };"#;
+        let p1 = Policy::from_str(policy_src).unwrap();
+
+        let json = p1.to_json().unwrap();
+
+        let p2 = Policy::from_json(None, json).unwrap();
+        assert_eq!(p1.to_string(), p2.to_string());
```
Comment (cdisselkoen) [inline cedar-policy/src/tests.rs:3275]: should we consider `assert_eq!(p1, p2);` instead?

File: cedar-policy/src/tests.rs (hunk 1 above)
Comment (cdisselkoen) [reply cedar-policy/src/tests.rs:3262]: +1

File: cedar-policy-core/src/est/expr.rs [hunk 4]
```diff
@@ -895,13 +934,27 @@ impl TryFrom<&Node<Option<cst::Relation>>> for Expr {
...
+                    .map(|expr| expr.into_pattern(&mut errs))
+                {
+                    Some(Some(pat)) => Ok(Expr::like(
+                        target_expr,
+                        pat.into_iter().map(PatternElem::from),
+                    )),
+                    _ => {
+                        if errs.is_empty() {
+                            Err(pattern
+                                .to_ast_err(ToASTErrorKind::InvalidPattern(
```
Comment (john-h-kastner-aws) [inline cedar-policy-core/src/est/expr.rs:949]: This case is kind of odd. I _think_ it should only ever happen if `pattern.ok_or_missing()?` returns an `Err` result, so the `InvalidPattern` error shouldn't be reachable

File: cedar-policy-core/src/est/expr.rs [hunk 5]
```diff
@@ -1551,7 +1604,12 @@ impl std::fmt::Display for ExprNoExt {
                 attr.escape_debug()
             ),
             ExprNoExt::Like { left, pattern } => {
-                write!(f, "{} like \"{}\"", maybe_with_parens(left), pattern) // intentionally not using .escape_debug() for pattern
+                write!(
+                    f,
+                    "{} like \"{}\"",
+                    maybe_with_parens(left),
+                    crate::ast::Pattern::from(pattern.clone())
+                ) // intentionally not using .escape_debug() for pattern
```
Comment (john-h-kastner-aws) [inline cedar-policy-core/src/est/expr.rs:1612]: Update this comment?

**Review by john-h-kastner-aws — APPROVED** [review]

File: cedar-policy/src/tests.rs (hunk 1 above)
Comment (john-h-kastner-aws) [reply cedar-policy/src/tests.rs:3260]: could still use these test cases

File: cedar-policy-core/src/est/expr.rs (hunk 4 above)
Comment (shaobo-he-aws) [reply cedar-policy-core/src/est/expr.rs:949]: Yes, it makes sense. Revised.

File: cedar-policy-core/src/est/expr.rs (hunk 5 above)
Comment (shaobo-he-aws) [reply cedar-policy-core/src/est/expr.rs:1612]: Done.

File: cedar-policy/src/tests.rs (hunk 3 above)
Comment (shaobo-he-aws) [reply cedar-policy/src/tests.rs:3273]: No, I don't think they are equal. For example, policy ids and lossless representations are different.

File: cedar-policy-core/src/est.rs [hunk 6]
```diff
@@ -2284,7 +2284,42 @@ mod test {
                                                 "attr": "email"
                                             }
                                         },
-                                        "pattern": "*@amazon.com"
```
Comment (aaronjeline) [inline cedar-policy-core/src/est.rs:2287]: Can we add a test demonstrating the behavior when `Literal` contains more both more than one character as well as a multibyte character?

**Review by aaronjeline — CHANGES_REQUESTED** [review]

File: cedar-policy-core/src/est.rs (hunk 6 above)
Comment (shaobo-he-aws) [reply cedar-policy-core/src/est.rs:2287]: Added a test.

**Review by aaronjeline — APPROVED** [review]
