### PR TITLE
fix for 418; some associated refactoring

### LINKED ISSUE #418: Schema-based JSON parsing does not accept unknowns when certain types are expected
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Cedar Parser

### Describe the bug

[Bug only affects experimental feature `partial-eval`]

Partial-evaluation unknowns can appear in JSON values via the extension function call `unknown()`.

Schema-based JSON parsing should accept a call to `unknown()` whenever it is expecting a value of any type whatsoever.

Currently, schema-based JSON parsing does not accept a call to `unknown()` when the expected type is an entity type, set type, or record type.

For instance, with the schema and entities given below, we get the error
```
  × failed to parse entities from file entities.json
  ├─▶ error during entity deserialization: in attribute `foo` on `a::""`, expected a literal entity reference, but got `{"__extn":
  │   {"fn":"unknown","arg":"123"}}`
```

### Expected behavior

Schema-based JSON parsing should accept a call to `unknown()` whenever it is expecting a value of any type whatsoever.

For instance, the schema and entities below should parse with no errors, when `partial-eval` is enabled.

### Reproduction steps

With `partial-eval` feature enabled:

`schema.json`
```json
{ "": {
   "entityTypes": {
       "a": {
           "shape": {
               "type": "Record",
               "attributes": {
                    "foo": { "type": "Entity", "name": "b" },
                    "bar": { "type": "Set", "element": { "type": "Long" } },
                    "baz": { "type": "Record", "attributes": { "z": { "type": "Boolean" } } }
               }
           }
       },
       "b": {}
   },
   "actions": {
       "view": {
            "appliesTo": {
                "principalTypes": ["a"],
                "resourceTypes": ["a"]
            }
       }
   }
} }
```

`entities.json`
```json
[
    {
        "uid": { "type": "a", "id": "" } ,
        "attrs": {
            "foo": { "__extn": { "fn": "unknown", "arg": "123" } },
            "bar": { "__extn": { "fn": "unknown", "arg": "456" } },
            "baz": { "__extn": { "fn": "unknown", "arg": "789" } }
        },
        "parents": []
    }
]
```

`request.json`
```json
{
    "principal": "a::\"\"",
    "action": "Action::\"view\"",
    "resource": "a::\"\"",
    "context": {}
}
```

`policies.cedar` can be empty.

Then, 
```console
cargo run -- authorize --schema schema.json --entities entities.json --request-json request.json --policies policies.cedar
```

You should see the error referred to above.

Reproducing this would be a little easier with #415 :)

### Code Snippet

_No response_

### Log output

_No response_

### Additional configuration

`partial-eval` feature enabled

### Operating  System

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by cdisselkoen**
## Description of changes

Fixes #418 and does a bit of associated refactoring.

One consequence of #418 is that computing the type of a `RestrictedExpr` is no longer always possible, due to `Unknown`s.  This affects error messages for some type mismatches, which used to report the expected and actual types, but now the actual type of the `RestrictedExpr` can't always be computed.  Rather than provide a different error message when the actual value is an unknown with no type, I have instead adjusted the error messages for these type mismatches to report the _expected type_ and _actual value_.  In my judgment, the resulting messages are clearer in some cases and less clear in others; see for yourself in the adjusted test expectations and let's discuss.

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A bug fix or other functionality change requiring a patch to `cedar-policy`.
- [x] A change (breaking or otherwise) that only impacts unreleased or experimental code.

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cdisselkoen** [comment]
maybe I'm blind but I don't see why the CI failed.  It says the actual error message was blah blah blah, and I can't see the difference between that actual error message and the expected error message for that test

File: cedar-policy-core/src/entities.rs [hunk 1]
```diff
@@ -2263,7 +2263,7 @@ mod schema_based_parsing_tests {
             .from_json_value(entitiesjson)
             .expect_err("should fail due to type mismatch on hr_contacts");
         assert!(
-            err.to_string().contains(r#"in attribute `hr_contacts` on `Employee::"12UA45"`, type mismatch: attribute was expected to have type (set of (entity of type `HR`)), but actually has type record"#),
+            err.to_string().contains(r#"in attribute `hr_contacts` on `Employee::"12UA45"`, type mismatch: attribute was expected to have type (set of (entity of type `HR`)), but it does not: `{"id": "aaaaa", "type": "HR"}`"#),
```
Comment (andrewmwells-amazon) [inline cedar-policy-core/src/entities.rs:2266]: I think this error message is significantly worse than the old one.

Comment (cdisselkoen) [reply cedar-policy-core/src/entities.rs:2266]: On the whole do you think the new error messages are on average worse than the old ones?  I agree this one is worse; I think some others are improved.  But if the change is on average for the negative, I can revert and just make an uglier message in the Unknown case

File: cedar-policy-core/src/entities/conformance.rs [hunk 2]
```diff
@@ -248,6 +260,14 @@ pub enum TypeOfRestrictedExprError {
     /// call the extension function, but to get metadata about it
     #[error(transparent)]
     ExtensionFunctionLookup(#[from] ExtensionFunctionLookupError),
+    /// Trying to compute the type of a restricted expression which contains
+    /// an [`Unknown`] that has insufficient type information associated in
+    /// order to compute the `SchemaType`
+    #[error("can't compute SchemaType because of insufficient type information for `{unknown}`")]
```
Comment (khieta) [inline cedar-policy-core/src/entities/conformance.rs:266]: nit
```suggestion
    #[error("cannot compute type because of insufficient type information for `{unknown}`")]
```

**Review by andrewmwells-amazon — APPROVED** [review]
