### PR TITLE
Use human friendly type format for type error display

### LINKED ISSUE #242: Better error messages for `Unexpected type` errors
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Schemas and Validation

### Describe the bug

If we replace the Policy 2 of the TinyTodo example like this,

```
// Policy 2: A User can see a List if they are either a reader or editor
permit (
    principal,
    action == Action::"GetList",
    resource
)
when { 3 < resource.readers || principal in resource.editors };
```

We get error messages,

```
Unexpected type. Expected {"type":"Long"} but saw {"type":"Entity","name":"Team"}
```

### Expected behavior

This error message could be more readable like `Expected type 'Long' but saw entity type 'Team'`

### Reproduction steps

1. Replace Policy 2
2. Run `cedar validate --schema tinytodo.cedarschema.json --policies policies.cedar`

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

### Additional configuration

_No response_

### Operating  System

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by john-h-kastner-aws**
Fix #242

This required a way to print out internal types that aren't accepted by the parser. I used a namespace `__cedar::internal` for this, so, for example, a type error that expects any set will say that it expects `Set<__cedar::internal::Any>`.

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A bug fix or other functionality change requiring a patch to `cedar-policy`.

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: cedar-policy-validator/src/human_schema/to_json_schema.rs [hunk 1]
```diff
@@ -47,6 +47,20 @@ pub fn custom_schema_to_json_schema(
     Ok((SchemaFragment(fragment), warnings.into_iter()))
 }
 
+/// Convert a custom type AST into the JSON representation of the type.
+/// Conversion is done in an empty context.
+pub fn custom_type_to_json_type(ty: Node<Type>) -> Result<SchemaType, ToJsonSchemaErrors> {
```
Comment (khieta) [inline cedar-policy-validator/src/human_schema/to_json_schema.rs:52]: Why "custom" type? Isn't it just the internal Cedar type?

(Context: I was confused by the name at first because I was trying to figure out how it related to `commonType` definitions in the JSON / `type` declarations in the new schema syntax)

File: cedar-policy-validator/src/types.rs [hunk 2]
```diff
@@ -2393,13 +2319,29 @@ mod test {
...
-        assert_displays_as(Type::Never, r#"{"type":"Never"}"#);
-        assert_displays_as(Type::True, r#"{"type":"True"}"#);
-        assert_displays_as(Type::False, r#"{"type":"False"}"#);
-        assert_displays_as(Type::any_set(), r#"{"type":"Set"}"#);
-        assert_displays_as(Type::any_entity_reference(), r#"{"type":"Entity"}"#);
+    fn test_type_display() {
+        // Entity types don't roundtrip because the human format type parser
+        // checks that they are defined already, so we'd need to provide a
+        // complete schema. TODO: the final stage of schema parsing already does
+        // this. Can we remove duplicated checks from human schema parsing?
```
Comment (khieta) [inline cedar-policy-validator/src/types.rs:2328]: Would be good to address this TODO in the PR, or file an issue for later & add the issue number to the comment

**Review by khieta — APPROVED** [review]
Left a couple minor comments. This will make error messages much more readable!

**Review by shaobo-he-aws — APPROVED** [review]

File: cedar-policy-validator/src/human_schema/to_json_schema.rs (hunk 1 above)
Comment (john-h-kastner-aws) [reply cedar-policy-validator/src/human_schema/to_json_schema.rs:52]: Just copied the phrasing from another function in this file. We could perhaps do a consistency pass so that we call the new schema format one name everywhere.

File: cedar-policy-validator/src/types.rs (hunk 2 above)
Comment (john-h-kastner-aws) [reply cedar-policy-validator/src/types.rs:2328]: I think it's not necessarily an easy change. #711
